
#- Carsten's PDK. Borders, symbols, loop stability
cpdk:
  remote: git@github.com:wulffern/cpdk.git
  revision: main


tech_sky130A:
  remote: git@github.com:wulffern/tech_sky130A.git
  revision: main

#- Transistor library (sky130B,sch,lay)
# used in simulation
sun_tr_sky130nm:
  remote: git@github.com:wulffern/sun_tr_sky130nm.git
  revision: main
