name: DOCS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "docs"
  cancel-in-progress: true

jobs:
  docs:
    uses: analogicus/jnw-actions/.github/workflows/docs.yaml@main
    #uses: ./tmp/.github/workflows/docs.yaml
