name: DOCS

on:
  push:
    branches: ["main"]
    paths:
      - '**.md'
      - 'documents/**'
      - 'media/**'
      - 'design/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "docs"
  cancel-in-progress: true

jobs:
  docs:
    uses: analogicus/jnw-actions/.github/workflows/docs.yaml@main
    permissions:
      contents: read
      pages: write
      id-token: write
