name: DRC

on:
  push:
    branches: ["main"]
    paths:
      - 'design/**.mag'
  workflow_dispatch:

concurrency:
  group: "drc"
  cancel-in-progress: true

jobs:
  drc:
    uses: analogicus/jnw-actions/.github/workflows/drc.yaml@main
    #uses: ./tmp/.github/workflows/drc.yaml
