name: GDS

on:
  push:
    branches: ["main"]
    paths:
      - 'design/**.mag'
  workflow_dispatch:

concurrency:
  group: "gds"
  cancel-in-progress: true

jobs:
  gds:
    uses: analogicus/jnw-actions/.github/workflows/gds.yaml@main
    #uses: ./tmp/.github/workflows/gds.yaml
