name: LVS

on:
  #push:
  #  branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "lvs"
  cancel-in-progress: true

jobs:
  gds:
    uses: analogicus/jnw-actions/.github/workflows/lvs.yaml@main
    #uses: ./tmp/.github/workflows/lvs.yaml
